m = "  Merhaba TON Dunyasi  "
print(trim(%m%))
print(upper(%m%.trim()))
print(%m%.trim().lower())
print(%m%.trim().split(" "))
print(%m%.contains("TON"), %m%.trim().starts("Mer"), %m%.trim().ends("si"))
print(%m%.trim().replace("TON", "TNL"))
print(len("merhaba"), "merhaba".upper())
print(join(["a", "b", "c"], "-"))
print("a,b,c".split(","))
print("merhaba".slice(0, 3), "merhaba".reverse())
print("ton".title(), "TON".lower())
print("x".pad(5, "."), "x".pad(5, ".", sag: false))
print("2024-05-01".split("-")[0])
print("a1b2".matches("[0-9]"))
print("merhaba dunya".find("dunya"))
print(number("42") + 1, number("3.5"), text(42) + "!")
print(text(3.14159, 2))
print(chars("ton"), code("A"), char(66))
print("cok    bosluk   var".clean())
